# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'add_plant.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialog, QDialogButtonBox,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QSizePolicy, QWidget)

class Ui_AddPlantWindow(object):
    def setupUi(self, AddPlantWindow):
        if not AddPlantWindow.objectName():
            AddPlantWindow.setObjectName(u"AddPlantWindow")
        AddPlantWindow.resize(590, 300)
        AddPlantWindow.setMinimumSize(QSize(590, 300))
        AddPlantWindow.setMaximumSize(QSize(10000, 100000))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 179))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush2 = QBrush(QColor(64, 159, 63, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        brush3 = QBrush(QColor(165, 204, 159, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        AddPlantWindow.setPalette(palette)
        self.confirm_plant = QDialogButtonBox(AddPlantWindow)
        self.confirm_plant.setObjectName(u"confirm_plant")
        self.confirm_plant.setGeometry(QRect(470, 110, 81, 241))
        self.confirm_plant.setOrientation(Qt.Orientation.Vertical)
        self.confirm_plant.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.select_icon = QLabel(AddPlantWindow)
        self.select_icon.setObjectName(u"select_icon")
        self.select_icon.setGeometry(QRect(340, 40, 71, 16))
        font = QFont()
        font.setBold(True)
        self.select_icon.setFont(font)
        self.search_bar = QLineEdit(AddPlantWindow)
        self.search_bar.setObjectName(u"search_bar")
        self.search_bar.setGeometry(QRect(110, 30, 113, 21))
        self.search_plant_text = QLabel(AddPlantWindow)
        self.search_plant_text.setObjectName(u"search_plant_text")
        self.search_plant_text.setGeometry(QRect(130, 10, 81, 16))
        self.search_plant_text.setFont(font)
        self.name_input = QLineEdit(AddPlantWindow)
        self.name_input.setObjectName(u"name_input")
        self.name_input.setGeometry(QRect(450, 80, 121, 21))
        self.choose_name = QLabel(AddPlantWindow)
        self.choose_name.setObjectName(u"choose_name")
        self.choose_name.setGeometry(QRect(470, 60, 91, 16))
        self.choose_name.setFont(font)
        self.all_plants_list = QListWidget(AddPlantWindow)
        self.all_plants_list.setObjectName(u"all_plants_list")
        self.all_plants_list.setGeometry(QRect(60, 60, 221, 201))
        self.icon_list = QListWidget(AddPlantWindow)
        self.icon_list.setObjectName(u"icon_list")
        self.icon_list.setGeometry(QRect(320, 61, 101, 201))
        self.icon_list.setIconSize(QSize(50, 50))
        self.search_frame = QLabel(AddPlantWindow)
        self.search_frame.setObjectName(u"search_frame")
        self.search_frame.setGeometry(QRect(0, 30, 321, 261))
        self.search_frame.setPixmap(QPixmap(u"../art/list_art.png"))
        self.search_frame.setScaledContents(True)
        self.icon_frame = QLabel(AddPlantWindow)
        self.icon_frame.setObjectName(u"icon_frame")
        self.icon_frame.setGeometry(QRect(290, 30, 148, 261))
        self.icon_frame.setPixmap(QPixmap(u"../art/list_art.png"))
        self.icon_frame.setScaledContents(True)
        self.small_logo = QLabel(AddPlantWindow)
        self.small_logo.setObjectName(u"small_logo")
        self.small_logo.setGeometry(QRect(470, 190, 91, 81))
        self.small_logo.setPixmap(QPixmap(u"../art/Plantfolio_logo_small.png"))
        self.small_logo.setScaledContents(True)
        self.article_title = QLabel(AddPlantWindow)
        self.article_title.setObjectName(u"article_title")
        self.article_title.setGeometry(QRect(450, 170, 131, 21))
        self.article_image = QLabel(AddPlantWindow)
        self.article_image.setObjectName(u"article_image")
        self.article_image.setGeometry(QRect(450, 190, 131, 101))
        self.article_image.setScaledContents(True)
        self.icon_frame.raise_()
        self.search_frame.raise_()
        self.icon_list.raise_()
        self.all_plants_list.raise_()
        self.confirm_plant.raise_()
        self.select_icon.raise_()
        self.search_bar.raise_()
        self.search_plant_text.raise_()
        self.name_input.raise_()
        self.choose_name.raise_()
        self.small_logo.raise_()
        self.article_title.raise_()
        self.article_image.raise_()

        self.retranslateUi(AddPlantWindow)
        self.confirm_plant.accepted.connect(AddPlantWindow.accept)
        self.confirm_plant.rejected.connect(AddPlantWindow.reject)

        QMetaObject.connectSlotsByName(AddPlantWindow)
    # setupUi

    def retranslateUi(self, AddPlantWindow):
        AddPlantWindow.setWindowTitle(QCoreApplication.translate("AddPlantWindow", u"Add plant", None))
        self.select_icon.setText(QCoreApplication.translate("AddPlantWindow", u"Select icon", None))
        self.search_plant_text.setText(QCoreApplication.translate("AddPlantWindow", u"Search plant", None))
        self.choose_name.setText(QCoreApplication.translate("AddPlantWindow", u"Choose a name", None))
        self.search_frame.setText("")
        self.icon_frame.setText("")
        self.small_logo.setText("")
        self.article_title.setText("")
        self.article_image.setText("")
    # retranslateUi

