# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'parent_window.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QListView, QListWidget, QListWidgetItem, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        if not MainMenu.objectName():
            MainMenu.setObjectName(u"MainMenu")
        MainMenu.resize(650, 475)
        MainMenu.setMinimumSize(QSize(650, 475))
        MainMenu.setMaximumSize(QSize(650, 475))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 179))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush2 = QBrush(QColor(64, 159, 63, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        brush3 = QBrush(QColor(165, 204, 159, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        MainMenu.setPalette(palette)
        self.centralwidget = QWidget(MainMenu)
        self.centralwidget.setObjectName(u"centralwidget")
        self.PlantFolio_Icon = QLabel(self.centralwidget)
        self.PlantFolio_Icon.setObjectName(u"PlantFolio_Icon")
        self.PlantFolio_Icon.setGeometry(QRect(110, -5, 421, 131))
        self.PlantFolio_Icon.setPixmap(QPixmap(u"../art/Plantfolio_logo.png"))
        self.PlantFolio_Icon.setScaledContents(True)
        self.open_room = QPushButton(self.centralwidget)
        self.open_room.setObjectName(u"open_room")
        self.open_room.setGeometry(QRect(50, 380, 75, 24))
        self.open_notifier = QPushButton(self.centralwidget)
        self.open_notifier.setObjectName(u"open_notifier")
        self.open_notifier.setGeometry(QRect(430, 380, 75, 24))
        self.Notification_list = QListWidget(self.centralwidget)
        self.Notification_list.setObjectName(u"Notification_list")
        self.Notification_list.setGeometry(QRect(430, 180, 180, 181))
        self.Notification_list.setFrameShape(QFrame.Shape.StyledPanel)
        self.Notification_list.setViewMode(QListView.ViewMode.ListMode)
        self.open_recommender = QPushButton(self.centralwidget)
        self.open_recommender.setObjectName(u"open_recommender")
        self.open_recommender.setGeometry(QRect(260, 200, 111, 31))
        self.room_list = QListWidget(self.centralwidget)
        self.room_list.setObjectName(u"room_list")
        self.room_list.setGeometry(QRect(50, 181, 180, 180))
        self.water_all = QPushButton(self.centralwidget)
        self.water_all.setObjectName(u"water_all")
        self.water_all.setGeometry(QRect(280, 140, 75, 24))
        self.water_all.setFlat(False)
        self.add_room = QPushButton(self.centralwidget)
        self.add_room.setObjectName(u"add_room")
        self.add_room.setGeometry(QRect(130, 380, 75, 24))
        self.all_plants = QPushButton(self.centralwidget)
        self.all_plants.setObjectName(u"all_plants")
        self.all_plants.setGeometry(QRect(280, 170, 75, 24))
        self.sort_notifications_by = QComboBox(self.centralwidget)
        self.sort_notifications_by.addItem("")
        self.sort_notifications_by.addItem("")
        self.sort_notifications_by.addItem("")
        self.sort_notifications_by.setObjectName(u"sort_notifications_by")
        self.sort_notifications_by.setGeometry(QRect(420, 140, 80, 24))
        self.refresh_notifications = QPushButton(self.centralwidget)
        self.refresh_notifications.setObjectName(u"refresh_notifications")
        self.refresh_notifications.setGeometry(QRect(500, 140, 121, 31))
        self.notification_list_frame = QLabel(self.centralwidget)
        self.notification_list_frame.setObjectName(u"notification_list_frame")
        self.notification_list_frame.setGeometry(QRect(380, 150, 261, 241))
        self.notification_list_frame.setPixmap(QPixmap(u"../art/list_art.png"))
        self.notification_list_frame.setScaledContents(True)
        self.room_list_frame = QLabel(self.centralwidget)
        self.room_list_frame.setObjectName(u"room_list_frame")
        self.room_list_frame.setGeometry(QRect(0, 150, 261, 241))
        self.room_list_frame.setPixmap(QPixmap(u"../art/list_art.png"))
        self.room_list_frame.setScaledContents(True)
        self.instructions_button = QPushButton(self.centralwidget)
        self.instructions_button.setObjectName(u"instructions_button")
        self.instructions_button.setGeometry(QRect(280, 270, 75, 24))
        self.save_button = QPushButton(self.centralwidget)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setGeometry(QRect(290, 300, 51, 24))
        MainMenu.setCentralWidget(self.centralwidget)
        self.room_list_frame.raise_()
        self.notification_list_frame.raise_()
        self.PlantFolio_Icon.raise_()
        self.open_room.raise_()
        self.open_notifier.raise_()
        self.Notification_list.raise_()
        self.open_recommender.raise_()
        self.room_list.raise_()
        self.water_all.raise_()
        self.add_room.raise_()
        self.all_plants.raise_()
        self.sort_notifications_by.raise_()
        self.refresh_notifications.raise_()
        self.instructions_button.raise_()
        self.save_button.raise_()
        self.menubar = QMenuBar(MainMenu)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 650, 33))
        MainMenu.setMenuBar(self.menubar)
        self.statusBar = QStatusBar(MainMenu)
        self.statusBar.setObjectName(u"statusBar")
        MainMenu.setStatusBar(self.statusBar)

        self.retranslateUi(MainMenu)

        self.open_room.setDefault(True)
        self.open_notifier.setDefault(True)
        self.open_recommender.setDefault(True)
        self.water_all.setDefault(True)
        self.add_room.setDefault(True)
        self.all_plants.setDefault(True)
        self.refresh_notifications.setDefault(True)
        self.instructions_button.setDefault(True)
        self.save_button.setDefault(True)


        QMetaObject.connectSlotsByName(MainMenu)
    # setupUi

    def retranslateUi(self, MainMenu):
        MainMenu.setWindowTitle(QCoreApplication.translate("MainMenu", u"Plantfolio", None))
        self.PlantFolio_Icon.setText("")
        self.open_room.setText(QCoreApplication.translate("MainMenu", u"Open Room", None))
        self.open_notifier.setText(QCoreApplication.translate("MainMenu", u"Notifications", None))
        self.open_recommender.setText(QCoreApplication.translate("MainMenu", u"Recommendations", None))
        self.water_all.setText(QCoreApplication.translate("MainMenu", u"Water all", None))
        self.add_room.setText(QCoreApplication.translate("MainMenu", u"Add Room", None))
        self.all_plants.setText(QCoreApplication.translate("MainMenu", u"All Plants", None))
        self.sort_notifications_by.setItemText(0, QCoreApplication.translate("MainMenu", u"day", None))
        self.sort_notifications_by.setItemText(1, QCoreApplication.translate("MainMenu", u"type", None))
        self.sort_notifications_by.setItemText(2, QCoreApplication.translate("MainMenu", u"weight", None))

        self.refresh_notifications.setText(QCoreApplication.translate("MainMenu", u"refresh notifications", None))
        self.notification_list_frame.setText("")
        self.room_list_frame.setText("")
        self.instructions_button.setText(QCoreApplication.translate("MainMenu", u"Instructions", None))
        self.save_button.setText(QCoreApplication.translate("MainMenu", u"Save", None))
    # retranslateUi

