# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'plant_view.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QLabel,
    QListWidget, QListWidgetItem, QMainWindow, QPushButton,
    QSizePolicy, QTextEdit, QWidget)

class Ui_PlantViewWindow(object):
    def setupUi(self, PlantViewWindow):
        if not PlantViewWindow.objectName():
            PlantViewWindow.setObjectName(u"PlantViewWindow")
        PlantViewWindow.resize(557, 398)
        PlantViewWindow.setMinimumSize(QSize(531, 0))
        PlantViewWindow.setMaximumSize(QSize(5310, 4010))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 179))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush2 = QBrush(QColor(64, 159, 63, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        brush3 = QBrush(QColor(165, 204, 159, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        PlantViewWindow.setPalette(palette)
        PlantViewWindow.setAutoFillBackground(False)
        self.centralwidget = QWidget(PlantViewWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.plant_icon = QLabel(self.centralwidget)
        self.plant_icon.setObjectName(u"plant_icon")
        self.plant_icon.setGeometry(QRect(20, 20, 111, 141))
        self.plant_icon.setPixmap(QPixmap(u"../art/all plants/plant_2_healthy.png"))
        self.plant_icon.setScaledContents(True)
        self.water_plant = QPushButton(self.centralwidget)
        self.water_plant.setObjectName(u"water_plant")
        self.water_plant.setGeometry(QRect(242, 220, 121, 31))
        icon = QIcon()
        icon.addFile(u"../art/water.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.water_plant.setIcon(icon)
        self.water_plant.setIconSize(QSize(32, 32))
        self.feed_plant = QPushButton(self.centralwidget)
        self.feed_plant.setObjectName(u"feed_plant")
        self.feed_plant.setGeometry(QRect(242, 260, 121, 31))
        icon1 = QIcon()
        icon1.addFile(u"../art/nutrition.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.feed_plant.setIcon(icon1)
        self.feed_plant.setIconSize(QSize(32, 32))
        self.plant_health_text = QLabel(self.centralwidget)
        self.plant_health_text.setObjectName(u"plant_health_text")
        self.plant_health_text.setGeometry(QRect(40, 160, 151, 21))
        self.plant_name = QLabel(self.centralwidget)
        self.plant_name.setObjectName(u"plant_name")
        self.plant_name.setGeometry(QRect(20, 180, 221, 31))
        self.plant_name.setMinimumSize(QSize(221, 31))
        self.sun_status = QLabel(self.centralwidget)
        self.sun_status.setObjectName(u"sun_status")
        self.sun_status.setGeometry(QRect(130, 0, 61, 51))
        self.sun_status.setPixmap(QPixmap(u"../art/full_sun.png"))
        self.sun_status.setScaledContents(True)
        self.preff_sunlight_text = QLabel(self.centralwidget)
        self.preff_sunlight_text.setObjectName(u"preff_sunlight_text")
        self.preff_sunlight_text.setGeometry(QRect(40, 240, 201, 16))
        self.preff_sunlight_icon = QLabel(self.centralwidget)
        self.preff_sunlight_icon.setObjectName(u"preff_sunlight_icon")
        self.preff_sunlight_icon.setGeometry(QRect(0, 230, 41, 31))
        self.preff_sunlight_icon.setPixmap(QPixmap(u"../art/half_shade.png"))
        self.preff_sunlight_icon.setScaledContents(True)
        self.scientific_name = QLabel(self.centralwidget)
        self.scientific_name.setObjectName(u"scientific_name")
        self.scientific_name.setGeometry(QRect(20, 210, 221, 21))
        self.water_frequency_text = QLabel(self.centralwidget)
        self.water_frequency_text.setObjectName(u"water_frequency_text")
        self.water_frequency_text.setGeometry(QRect(20, 270, 221, 16))
        self.last_nutrition = QLabel(self.centralwidget)
        self.last_nutrition.setObjectName(u"last_nutrition")
        self.last_nutrition.setGeometry(QRect(20, 290, 211, 16))
        self.note_text = QTextEdit(self.centralwidget)
        self.note_text.setObjectName(u"note_text")
        self.note_text.setGeometry(QRect(242, 60, 151, 141))
        self.notes_header = QLabel(self.centralwidget)
        self.notes_header.setObjectName(u"notes_header")
        self.notes_header.setGeometry(QRect(242, 40, 49, 16))
        font = QFont()
        font.setBold(True)
        self.notes_header.setFont(font)
        self.manual_health = QCheckBox(self.centralwidget)
        self.manual_health.setObjectName(u"manual_health")
        self.manual_health.setGeometry(QRect(240, 340, 131, 20))
        self.spot_info = QLabel(self.centralwidget)
        self.spot_info.setObjectName(u"spot_info")
        self.spot_info.setGeometry(QRect(380, 20, 61, 16))
        self.spot_info.setFont(font)
        self.spot_id = QLabel(self.centralwidget)
        self.spot_id.setObjectName(u"spot_id")
        self.spot_id.setGeometry(QRect(400, 50, 111, 20))
        self.spot_sunlight = QLabel(self.centralwidget)
        self.spot_sunlight.setObjectName(u"spot_sunlight")
        self.spot_sunlight.setGeometry(QRect(402, 80, 111, 20))
        self.humidity = QLabel(self.centralwidget)
        self.humidity.setObjectName(u"humidity")
        self.humidity.setGeometry(QRect(400, 110, 101, 20))
        self.temperature = QLabel(self.centralwidget)
        self.temperature.setObjectName(u"temperature")
        self.temperature.setGeometry(QRect(402, 140, 111, 20))
        self.water_log_header = QLabel(self.centralwidget)
        self.water_log_header.setObjectName(u"water_log_header")
        self.water_log_header.setGeometry(QRect(402, 200, 61, 16))
        self.water_log_header.setFont(font)
        self.water_log_list = QListWidget(self.centralwidget)
        self.water_log_list.setObjectName(u"water_log_list")
        self.water_log_list.setGeometry(QRect(402, 220, 121, 81))
        self.health_setter = QComboBox(self.centralwidget)
        self.health_setter.addItem("")
        self.health_setter.addItem("")
        self.health_setter.addItem("")
        self.health_setter.addItem("")
        self.health_setter.setObjectName(u"health_setter")
        self.health_setter.setGeometry(QRect(240, 360, 80, 24))
        self.last_repotted = QLabel(self.centralwidget)
        self.last_repotted.setObjectName(u"last_repotted")
        self.last_repotted.setGeometry(QRect(20, 310, 211, 16))
        self.repot_plant = QPushButton(self.centralwidget)
        self.repot_plant.setObjectName(u"repot_plant")
        self.repot_plant.setGeometry(QRect(240, 300, 121, 31))
        icon2 = QIcon()
        icon2.addFile(u"../art/empty_pot.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.repot_plant.setIcon(icon2)
        self.add_delete_plant = QPushButton(self.centralwidget)
        self.add_delete_plant.setObjectName(u"add_delete_plant")
        self.add_delete_plant.setGeometry(QRect(14, 0, 101, 24))
        PlantViewWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PlantViewWindow)

        QMetaObject.connectSlotsByName(PlantViewWindow)
    # setupUi

    def retranslateUi(self, PlantViewWindow):
        PlantViewWindow.setWindowTitle(QCoreApplication.translate("PlantViewWindow", u"Plant View", None))
        self.plant_icon.setText("")
        self.water_plant.setText(QCoreApplication.translate("PlantViewWindow", u"Water plant", None))
        self.feed_plant.setText(QCoreApplication.translate("PlantViewWindow", u"Feed plant", None))
        self.plant_health_text.setText(QCoreApplication.translate("PlantViewWindow", u"Plant is healthy", None))
        self.plant_name.setText(QCoreApplication.translate("PlantViewWindow", u"Plant name here", None))
        self.sun_status.setText("")
        self.preff_sunlight_text.setText(QCoreApplication.translate("PlantViewWindow", u"preffered sunlight", None))
        self.preff_sunlight_icon.setText("")
        self.scientific_name.setText(QCoreApplication.translate("PlantViewWindow", u"scientific name", None))
        self.water_frequency_text.setText(QCoreApplication.translate("PlantViewWindow", u"Watering_frequency", None))
        self.last_nutrition.setText(QCoreApplication.translate("PlantViewWindow", u"Last fed", None))
        self.note_text.setHtml(QCoreApplication.translate("PlantViewWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.notes_header.setText(QCoreApplication.translate("PlantViewWindow", u"Notes", None))
        self.manual_health.setText(QCoreApplication.translate("PlantViewWindow", u"Manual health mode", None))
        self.spot_info.setText(QCoreApplication.translate("PlantViewWindow", u"Spot info", None))
        self.spot_id.setText(QCoreApplication.translate("PlantViewWindow", u"SpotID", None))
        self.spot_sunlight.setText(QCoreApplication.translate("PlantViewWindow", u"Sunlight", None))
        self.humidity.setText(QCoreApplication.translate("PlantViewWindow", u"humidity", None))
        self.temperature.setText(QCoreApplication.translate("PlantViewWindow", u"temperature", None))
        self.water_log_header.setText(QCoreApplication.translate("PlantViewWindow", u"Water log", None))
        self.health_setter.setItemText(0, QCoreApplication.translate("PlantViewWindow", u"Healthy", None))
        self.health_setter.setItemText(1, QCoreApplication.translate("PlantViewWindow", u"Slightly unhealthy", None))
        self.health_setter.setItemText(2, QCoreApplication.translate("PlantViewWindow", u"Unhealthy", None))
        self.health_setter.setItemText(3, QCoreApplication.translate("PlantViewWindow", u"Dead", None))

        self.last_repotted.setText(QCoreApplication.translate("PlantViewWindow", u"Last repotted", None))
        self.repot_plant.setText(QCoreApplication.translate("PlantViewWindow", u"Repot plant", None))
        self.add_delete_plant.setText(QCoreApplication.translate("PlantViewWindow", u"Add/Delete Plant", None))
    # retranslateUi

