image: python:3.12

before_script:
  # Required for pyside to work with pylint in a pipeline
  - apt update
  - apt install -y libgl1-mesa-glx libegl1 libxkbcommon-dev dbus
  - python -m pip install --upgrade pip
  - pip install pipenv
  - pipenv sync

stages:
  - Static Analysis
  - Test

mypy:
  stage: Static Analysis
  allow_failure: false # Warnings are ignored by the pipeline. Consider changing this everywhere
  script:
    - pipenv run mypy .

pylint:
  stage: Static Analysis
  allow_failure: false
  script:
    # Run pylint to generate human-readable and gitlab readable formats
    - pipenv run pylint --exit-zero --output-format=text -d C0116 project/ | tee /tmp/pylint.txt
    - pipenv run pylint --load-plugins=pylint_gitlab --output-format=gitlab-codeclimate project/ > codeclimate.json
  artifacts:
    expire_in: 7 days
    reports:
      codequality: codeclimate.json

tests:
  stage: Test
  allow_failure: false
  script:
    - pipenv run coverage run
    - pipenv run coverage report
    - pipenv run coverage xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    expire_in: 7 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
